const initialProducts = [
  {
    id: 1,
    name: 'Producto 1',
    description: 'Descripción breve del producto 1',
    tags: ['Tag1', 'Tag2'],
    price: 100,
    stock: 20,
    images: ['img1.jpg', 'img2.jpg'], // Añade las rutas de las imágenes
  },
  {
    id: 2,
    name: 'Producto 2',
    description: 'Descripción breve del producto 2',
    tags: ['Tag3', 'Tag4'],
    price: 200,
    stock: 15,
    images: ['img1.jpg', 'img2.jpg'],
  },
  {
    id: 3,
    name: 'Producto 3',
    description: 'Descripción breve del producto 3',
    tags: ['Tag5', 'Tag6'],
    price: 300,
    stock: 30,
    images: ['img1.jpg', 'img2.jpg'],
  },
  {
    id: 4,
    name: 'Producto 4',
    description: 'Descripción breve del producto 4',
    tags: ['Tag7', 'Tag8'],
    price: 400,
    stock: 10,
    images: ['img1.jpg', 'img2.jpg'],
  },
  {
    id: 5,
    name: 'Producto 5',
    description: 'Descripción breve del producto 5',
    tags: ['Tag9', 'Tag10'],
    price: 500,
    stock: 25,
    images: ['img1.jpg', 'img2.jpg'],
  },
  {
    id: 6,
    name: 'Producto 6',
    description: 'Descripción breve del producto 6',
    tags: ['Tag11', 'Tag12'],
    price: 600,
    stock: 40,
    images: ['img1.jpg', 'img2.jpg'],
  },
  {
    id: 7,
    name: 'Producto 7',
    description: 'Descripción breve del producto 7',
    tags: ['Tag13', 'Tag14'],
    price: 700,
    stock: 5,
    images: ['img1.jpg', 'img2.jpg'],
  },
  {
    id: 8,
    name: 'Producto 8',
    description: 'Descripción breve del producto 8',
    tags: ['Tag15', 'Tag16'],
    price: 800,
    stock: 60,
    images: ['img1.jpg', 'img2.jpg'],
  },
  {
    id: 9,
    name: 'Producto 9',
    description: 'Descripción breve del producto 9',
    tags: ['Tag17', 'Tag18'],
    price: 900,
    stock: 70,
    images: ['img1.jpg', 'img2.jpg'],
  },
  {
    id: 10,
    name: 'Producto 10',
    description: 'Descripción breve del producto 10',
    tags: ['Tag19', 'Tag20'],
    price: 1000,
    stock: 35,
    images: ['img1.jpg', 'img2.jpg'],
  },
];

export default initialProducts;
